USER_ID_FIELD: userId
ITEM_ID_FIELD: movieId
RATING_FIELD: rating
TIME_FIELD: timestamp

# dataset: goodreads

load_col:
  inter: [userId, movieId, rating, timestamp]

eval_args:
  group_by: user
  order: TO
  split: {RS: [0.8, 0.1, 0.1]}

use_gpu: True
gpu_id: 0
show_progress: True

MODEL_INPUT_TYPE: pairwise

embedding_size: 64

teacher_n_layers: 2
student_n_layers: 1

reg_weight_teacher: 1e-5
reg_weight_student: 1e-5

# Distillation strengths
lambda_pred_distill: 1.0
lambda_emb_distill: 1.0
lambda_contrast_reg: 0.1

# Distillation temperatures
temp_pred_distill: 1.0
temp_emb_distill: 1.0
temp_contrast_reg: 1.0

freeze_teacher: true

# others
epochs: 1
learning_rate: 1e-3
train_batch_size: 2048