use_gpu: True
gpu_id: 0
show_progress: True
train_neg_sample_args: ~
epochs: 30

# rsc15 dataset
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD: timestamp
load_col:
    inter: [user_id, item_id, timestamp]


eval_args:
    group_by: user
    order: TO
    split: {RS: [0.8, 0.1, 0.1]}
    mode: full

hidden_size: 100