USER_ID_FIELD: userId
ITEM_ID_FIELD: movieId
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
  inter: [userId, movieId, rating, timestamp]

eval_args:
  group_by: user
  order: TO
  split: {RS: [0.8, 0.1, 0.1]}

use_gpu: False
gpu_id: ""
show_progress: True

MODEL_INPUT_TYPE: pointwise

top_k: 50
epochs: 0