USER_ID_FIELD: userId
ITEM_ID_FIELD: movieId
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
  inter: [userId, movieId, rating, timestamp]

eval_args:
  group_by: user
  order: TO
  split: {RS: [0.8, 0.1, 0.1]}

use_gpu: False
gpu_id: ""
show_progress: True

MODEL_INPUT_TYPE: pairwise
embedding_size: 64
n_layers: 2

# others
epochs: 1
learning_rate: 1e-3
train_batch_size: 256

n_intents: 128
temp: 0.5
emb_reg: 1e-4
cen_reg: 1e-4
ssl_reg: 0.1
